### ISSUE TITLE
Test Snative -> EVM Connection

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#139]
In order to prepare for the eris:db -> eris:rt change we need to be able to test how our snative contracts are exposed into the EVM.

The current most utilized snative is an access gateway our permissions layer so it is a natural place to start. However, we also will need to test nameReg functionality as well.

While this functionality is currently exposed, it is not tested. Nor are there any examples for users wishing to leverage this functionality.

**Comment by compleatang** [comment]
if any one wants to help, just pull the `permsSNative` branch and run (from repo root) `tests/test.sh wip99` ...

**Comment by stevebakh** [comment]
I've created a simple experiment to test this functionality. I was hoping to be able to arbitrarily assign roles to accounts and have my contract code interrogate an account's permissions in order to determine if a request action is permitted. You can find the code and instructions here, if it helps: https://github.com/stevebakh/eris-solidity-roles-experiment

There's a _very_ good chance that I'm doing something wrong (as I'm just learning about Solidity and Eris at the same time), but the logs seem to indicate that the `has_role` function is always returning true, allowing an account without the relevant role to perform an action.

**Comment by compleatang** [comment]
@stevebakh I've got it worked out; just need to fixup tests and push relevant code. ETA tomorrow late afternoon Europe.

**Comment by compleatang** [comment]
@stevebakh check out the above PR for the solidity contract and epm.yaml I used but everything is now testing and green. 

I had to make some minor modifications to erisdb, so before you proceed with your testing run `docker pull quay.io/eris/erisdb:0.11.4` and you should be all set. Let me know if that does not solve the issue.
