### ISSUE TITLE
Error compiling contracts encoding/hex: odd length hex string -- error when using library

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-pm#209]
Hi,
With reference to https://github.com/eris-ltd/eris-cli/issues/590,
I have tried using library as specified in the latest samples. 
https://github.com/eris-ltd/eris-pm/blob/master/tests/fixtures/app35-library_handling/consuming-contract.sol

But the when trying to compile it gives error -- Error compiling contracts encoding/hex: odd length hex string.

My epm.yaml looks like this:

- name: arrayUtilAddr
  job:
    deploy:
      contract: ArrayUtil.sol
      instance: arraylib
      wait: true

- name: testAddr
  job:
    deploy:
      contract: test.sol
	  libraries: ArrayUtil:$arrayUtilAddr
          wait: true

In the test.sol i am using the library like --> 
using arraylib for uint[];

Is this library issue still not fixed? Or am I doing something wrong here???

--Required details: 

[1.11.2 ] `docker version`
[0.11.4] `eris version`
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

**Comment by compleatang** [comment]
Hi @somak12 the fix was just merged a few minutes ago into erisdb. The docker image will be pushed shortly, but in about 15 minutes you can run `docker pull quay.io/eris/erisdb:0.11.4` then you'll need to remove the chains' service container and then restart the chain with `eris chains stop -r chainName && eris chains start chainName` (note that when using the above command your data container will be preserved so the chain should reboot smoothly).

**Comment by somak12** [comment]
Ok. Will try after a while. Since the issue was closed in 20th June I got confused. Thanks @compleatang
