### ISSUE TITLE
Library tests failing similar to missing delegate opcode

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#212]
The two attached tests fail with 'seemingly' no return value; similar to the missing `delegatecall`.

MappingsLibTest was changed to use only one library and follows the examples in the Solidity doc:
https://solidity.readthedocs.io/en/develop/contracts.html#libraries
[MappingsLibTest.zip](https://github.com/eris-ltd/eris-pm/files/468796/MappingsLibTest.zip)

The ParentLibTest uses two libraries with one library calling the other.
[ParentLibTest.zip](https://github.com/eris-ltd/eris-pm/files/468797/ParentLibTest.zip)

Please confirm if this could be a bug or not.
Also note that the test used for #198 is successfully passing!

**Comment by jasonklein** [comment]
@j-h-scheufen, @VoR0220, @silasdavis, @benjaminbollen : please find attached an attempt at stripped down tests, consisting of one solidity file containing both a library, `LibReturner`, and a contract that uses it, `ReturnerTest`, and an `epm.yaml`. `LibReturner` has the relevant struct definitions and the `insert` function from the original `Mappings` library. There are 13 functions total, 6 of which return. The oddest result (to me) is that `withCondition` and `incStructMemberUintAndAssign` both return, but `withConditionAndIncStructMemberUintAndAssign` does not.

N.B.: With the exception of `explicitReturn`, which returns `1`, all of the functions should return `0`.
N.B.: I do not include `assert` jobs in the `epm.yaml`, because epm stops running jobs after a failed assertion.

In the words of The Chief on "Where in the world is Carmen Sandiego?", _good luck gumshoes!_

[LibReturnerTest.zip](https://github.com/eris-ltd/eris-pm/files/485013/LibReturnerTest.zip)

**Comment by silasdavis** [comment]
So I've tried to reduce this to a minimal example, and here is my result:

https://gist.github.com/silasdavis/b8a2ed236b31ead70bf2a674b9811923

It will help us out a lot if any downstream issues can be manipulated down to something as isolated as this if possible in the future.

It seems like we have an issue writing a field of a struct that is contained in a mapping when passed to a library. I'm going to play around with how it fare with other types of passed storage.

**Comment by silasdavis** [comment]
Playing around with this, it seems that there may be difficulty in writing to both arrays and mappings nested within a struct from within a library. See the following:

```javascript
library Returner {
	// Struct definitions used in Jan's Mappings library
    struct B32AddressMap {
        mapping (bytes32 => AddressElement) rows;
        AddressElement[] elems;
        AddressElement elem;
    }

    struct AddressElement {
        address value;
    }

	// Does not return
    // Insert function definition used in Jan's Mappings library
    function insert(B32AddressMap storage _map, bytes32 _key, address _value) returns (uint)
    {
        // Writing to a direct field is fine:
        _map.elem.value = _value;

        // But all of the these writes to a wrapped field fail independently:
        // 1.
        _map.rows[_key].value = _value; 
        
        // 2.
        var idx = _map.elems.length++;

        // 3.
        _map.elems[1].value = _value;
  		
        return 1;
    }
}


contract ReturnerTest {
	bytes32 constant KEY = "key";
	bytes32 constant LOCAL_KEY = "local_key";
	Returner.B32AddressMap b32AMap;

	// Does not return
	function insert() returns (uint) {
        // Done locally within this contract the following are fine:
        b32AMap.elems.length += 5;
        b32AMap.elems[0].value = msg.sender;
        b32AMap.rows[LOCAL_KEY].value = msg.sender;
        // Done via a library call the execution fails:
		return Returner.insert(b32AMap, KEY, msg.sender);		
	}
}
```

Writing to the first-level element `elem` is fine, but not when they are wrapped in a mapping or array. Perhaps there is an issue with how we point to the calling contracts storage or special casing on initialisation.

Also of some interest is we see the trace:

```
E(pc) 210 (op) SHA3           (st) 10   error on call: Insuffient gas
Wresume 000000000000000000000000C1389CFA5D8D2A757AEE916FD5DBDC136AEDC081 (0xc4212e9c28)
R(pc) 577 (op) ISZERO         (st) 7      == 0 = 1
n(pc) 578 (op) PUSH2          (st) 7     => 0x0000000000000000000000000000000000000000000000000000000000000002
E(pc) 581 (op) JUMPI          (st) 8     ~> 2 invalid jump dest PUSH1
```

the "Insuffient [sic] gas" message is curious, changing the gas limit doesn't make it go away, so may be a side-effect of some other badness.

**Comment by silasdavis** [comment]
So I may have a fix in the form of: https://github.com/eris-ltd/eris-db/pull/305.

I want to get a few more people's opinions first, because if that is the fix it means our handling of gas allowance for `CALL`s has always been wrong. Essentially we seem to have been passing a much smaller amount of gas to callees than we should have (we subtracted their entire gas limit before running them, and then passed that difference instead of passing their limit).

I have verified that this fix works with my test case. I will take a look with your original test @j-h-scheufen.

**Comment by silasdavis** [comment]
So I can confirm it also fixes your MappingsLibTest.yaml test case (passes with the "success" assertion).


Your LibTest.yaml doesn't pass, but I don't think those contracts are meant to do what you expect. In particularly your `birthday` function doesn't modify the storage object, it just takes unit passed by value, adds to it and does nothing. Also LibTest.yaml needs a `wait: true` directive.

**Comment by j-h-scheufen** [comment]
Verified fix based on clone `silas/delegate-call-master` which has been merged with PR https://github.com/eris-ltd/eris-db/pull/305
All previously failing tests now pass. Closing ticket.
