### ISSUE TITLE
pkgs do touches the contract.sol without change

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-pm#69]
It is really annoying as my editor warns me everytime after running pkgs do (am I sure to want to edit the file after it has been changed). I did a diff pre and after, and nothing changes. Except the time, so it is as if it just touches it.

Is there a way to prevent this?

**Comment by compleatang** [comment]
so the only way to prevent that is to not copy back out the contents of the contracts folder which could be fine as long as none of the artifacts of the contracts are not needed on the host / future stuff. which they shouldn't be for the most part. 

i guess we could refactor the copy out part of eris pkgs to only export the ABIs and the epm.json|epm.csv which would be the necessary artifacts for now. Although the current way is more extensible for using other frameworks as it just copies "everything" back out into the host (which is why your editor think the file changed). 

If this is annoying when developing contracts then probably we should change it.

**Comment by kootenpv** [comment]
I guess for now I'll work from a different directory myself and copy the dir to my apps folder.

**Comment by j-h-scheufen** [comment]
I have to agree with the 'annoying'. Depending on what editor I use, running a quick 'pkgs do' it triggers a re-indexing of the project sources. WebStorm, e.g., become unresponsive for 20 sec after running the epm to accomplish that.
It's not that annoying ... but the ticket has validity.

**Comment by compleatang** [comment]
this is a cli issue. https://github.com/eris-ltd/eris-cli/issues/539

closing here in favor of tracking in cli.
